### ISSUE TITLE
how to do the url rewrite, is it possible?

### ISSUE THREAD

**Issue by redguardtoo** [skeeto/emacs-web-server#11]
in angular application, for the url `http://localhost:4444/checklist` from url, I want the server map it to the real url `http://localhost:4444/#/checklist`.

See https://github.com/bdunklau/LittleBlueBird/wiki/URL-Rewriting-and-HTML5-in-AngularJS

**Comment by skeeto** [comment]
There's no specific high level option for this like you get with Apache,
but with simple-httpd you have full control over dispatch. When a
request arrives, simple-httpd calls the function prefixed with "httpd/"
that most closely matches the request path -- meaning you can accomplish
the same effect as a rewrite one way or another.

For example, if what you want is an HTTP redirect, define a servlet
using defservlet or defservlet* which calls httpd-redirect, passing it
the rewritten path. Or, if you want the redirect to be "silent," tail
call the desired servlet from the client-requested servlet.

**Comment by redguardtoo** [comment]
Since angular is for single page application. I'm actually requiring to convert all the URLs , so defservlet may not be helpful. For example, for any url "http://localhost/anything-here", I need server to actually use url "http://localhost/#/anything-here"

After reading the code, looks I need change of httpd-get-servlet, here is my patch:
```lisp
diff --git a/simple-httpd.el b/simple-httpd.el
index 9994e2c..fc97632 100644
--- a/simple-httpd.el
+++ b/simple-httpd.el
@@ -183,6 +183,9 @@
   :group 'simple-httpd
   :type 'hook)
 
+(defvar httpd-convert-uri-callback nil
+  "A defun to convert uri-path in httpd-get-servlet")
+
 (defvar httpd-server-name (format "simple-httpd (Emacs %s)" emacs-version)
   "String to use in the Server header.")
 
@@ -620,6 +623,9 @@ variable/value pairs, and the third is the fragment."
 
 (defun httpd-get-servlet (uri-path)
   "Determine the servlet to be executed for URI-PATH."
+  (if httpd-convert-uri-callback
+      (setq uri-path (httpd-convert-uri-callback uri-path)))
+
   (if (not httpd-servlets)
       'httpd/
     (cl-labels ((cat (x)
```

**Comment by skeeto** [comment]
I have an Angular app using simple-httpd called [elfeed-web](https://github.com/skeeto/elfeed/tree/master/web), so you *should* be able to do Angular+simple-httpd as-is. Here's how you'd do it in your case:

~~~el
(defservlet* ## "text/plain" (name)
  (princ (format "Hello, %s" (or name "anonymous"))))

(defservlet anything-here nil (path)
  (httpd-redirect t (format "/#%s" path)))
~~~

Note that `##` is the empty symbol, so that it matches the root of the server. Due to a bug that probably won't work in the version you currently have installed. I just pushed a commit (4b7a6bc) to fix that.

**Comment by redguardtoo** [comment]
what's the purpose of `defservle* **`? Can I avoid `defsevlet anything-here`? For example, if I have a new module "/checklist", I want to avoid writing "defservlet checklist" because I have many modules to create.

**Comment by skeeto** [comment]
The dispatch mechanism just finds a function prefixed with `httpd/` that matches some part of the request path. That function's job is to fill a (temp) buffer with the response and call `httpd-send-header` in it (as the current buffer). The `defservlet` macro does most of the work for you. So this:

~~~el
(defservlet* foo "text/plain" ()
  (princ "Hello, world!"))
~~~

Is equal to this:

~~~el
(defun httpd/foo (proc path query request)
  (with-temp-buffer
    (insert "Hello, world!")
    (httpd-send-header proc "text/plain" 200)))
~~~

The `*` part on `defservlet*` is because it's at a "higher level" than `defservlet` (the former builds on the latter). It has fancy pants argument binding stuff. For example,

~~~el
(defservlet* foo/:name "text/plain" (greeting)
  (princ (format "%s, %s!" (or greeting "Hello") (or name "anonymous"))))
~~~

Now if you visit `/foo` you get the message "Hello, anonymous!". And if you visit `/foo/chen?greeting=Hi` you get "Hi, chen!".
